# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Aug 04 19:11:09 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(486, 375)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "BESM Character Resolver", None, QtGui.QApplication.UnicodeUTF8))
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(38, 0))
        self.label_3.setBaseSize(QtCore.QSize(38, 0))
        self.label_3.setMidLineWidth(0)
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Notes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setMargin(0)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.notesEdit = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.notesEdit.sizePolicy().hasHeightForWidth())
        self.notesEdit.setSizePolicy(sizePolicy)
        self.notesEdit.setAutoFormatting(QtGui.QTextEdit.AutoAll)
        self.notesEdit.setReadOnly(False)
        self.notesEdit.setObjectName(_fromUtf8("notesEdit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.notesEdit)
        self.gridLayout_2.addLayout(self.formLayout_3, 0, 1, 1, 3)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Mind:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.mindSpin = QtGui.QSpinBox(self.centralwidget)
        self.mindSpin.setObjectName(_fromUtf8("mindSpin"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.mindSpin)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Soul:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.soulSpin = QtGui.QSpinBox(self.centralwidget)
        self.soulSpin.setObjectName(_fromUtf8("soulSpin"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.soulSpin)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Body:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.bodySpin = QtGui.QSpinBox(self.centralwidget)
        self.bodySpin.setObjectName(_fromUtf8("bodySpin"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.bodySpin)
        self.gridLayout_2.addLayout(self.formLayout, 1, 0, 1, 1)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Health:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.healthEdit = QtGui.QLineEdit(self.centralwidget)
        self.healthEdit.setEnabled(False)
        self.healthEdit.setObjectName(_fromUtf8("healthEdit"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.healthEdit)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Energy:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.energyEdit = QtGui.QLineEdit(self.centralwidget)
        self.energyEdit.setEnabled(False)
        self.energyEdit.setObjectName(_fromUtf8("energyEdit"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.energyEdit)
        self.gridLayout_2.addLayout(self.formLayout_4, 1, 1, 1, 1)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Combat:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.combatEdit = QtGui.QLineEdit(self.centralwidget)
        self.combatEdit.setEnabled(False)
        self.combatEdit.setObjectName(_fromUtf8("combatEdit"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.combatEdit)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Defense:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Shock:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.defenseEdit = QtGui.QLineEdit(self.centralwidget)
        self.defenseEdit.setEnabled(False)
        self.defenseEdit.setObjectName(_fromUtf8("defenseEdit"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.defenseEdit)
        self.shockEdit = QtGui.QLineEdit(self.centralwidget)
        self.shockEdit.setEnabled(False)
        self.shockEdit.setObjectName(_fromUtf8("shockEdit"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.shockEdit)
        self.gridLayout_2.addLayout(self.formLayout_5, 1, 3, 1, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.nameEdit = QtGui.QLineEdit(self.centralwidget)
        self.nameEdit.setObjectName(_fromUtf8("nameEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.nameEdit)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Age:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.ageEdit = QtGui.QLineEdit(self.centralwidget)
        self.ageEdit.setObjectName(_fromUtf8("ageEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.ageEdit)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_13)
        self.heightEdit = QtGui.QLineEdit(self.centralwidget)
        self.heightEdit.setObjectName(_fromUtf8("heightEdit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.heightEdit)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Weight:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_14)
        self.weightEdit = QtGui.QLineEdit(self.centralwidget)
        self.weightEdit.setObjectName(_fromUtf8("weightEdit"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.weightEdit)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Genre:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.genreSelection = QtGui.QComboBox(self.centralwidget)
        self.genreSelection.setObjectName(_fromUtf8("genreSelection"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.genreSelection)
        self.gridLayout_2.addLayout(self.formLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 486, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setSizeGripEnabled(True)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

