# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sat Aug 06 02:09:27 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(573, 753)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(10000000, 1000000))
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "BESM Character Resolver", None, QtGui.QApplication.UnicodeUTF8))
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.infoFormLayout = QtGui.QFormLayout()
        self.infoFormLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.infoFormLayout.setObjectName(_fromUtf8("infoFormLayout"))
        self.nameLabel = QtGui.QLabel(self.centralwidget)
        self.nameLabel.setText(QtGui.QApplication.translate("MainWindow", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLabel.setObjectName(_fromUtf8("nameLabel"))
        self.infoFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.nameLabel)
        self.nameEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameEdit.sizePolicy().hasHeightForWidth())
        self.nameEdit.setSizePolicy(sizePolicy)
        self.nameEdit.setObjectName(_fromUtf8("nameEdit"))
        self.infoFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.nameEdit)
        self.ageLabel = QtGui.QLabel(self.centralwidget)
        self.ageLabel.setText(QtGui.QApplication.translate("MainWindow", "Age:", None, QtGui.QApplication.UnicodeUTF8))
        self.ageLabel.setObjectName(_fromUtf8("ageLabel"))
        self.infoFormLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.ageLabel)
        self.ageEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ageEdit.sizePolicy().hasHeightForWidth())
        self.ageEdit.setSizePolicy(sizePolicy)
        self.ageEdit.setObjectName(_fromUtf8("ageEdit"))
        self.infoFormLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.ageEdit)
        self.heightLabel = QtGui.QLabel(self.centralwidget)
        self.heightLabel.setText(QtGui.QApplication.translate("MainWindow", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.heightLabel.setObjectName(_fromUtf8("heightLabel"))
        self.infoFormLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.heightLabel)
        self.heightEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightEdit.sizePolicy().hasHeightForWidth())
        self.heightEdit.setSizePolicy(sizePolicy)
        self.heightEdit.setObjectName(_fromUtf8("heightEdit"))
        self.infoFormLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.heightEdit)
        self.weightLabel = QtGui.QLabel(self.centralwidget)
        self.weightLabel.setText(QtGui.QApplication.translate("MainWindow", "Weight:", None, QtGui.QApplication.UnicodeUTF8))
        self.weightLabel.setObjectName(_fromUtf8("weightLabel"))
        self.infoFormLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.weightLabel)
        self.weightEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weightEdit.sizePolicy().hasHeightForWidth())
        self.weightEdit.setSizePolicy(sizePolicy)
        self.weightEdit.setObjectName(_fromUtf8("weightEdit"))
        self.infoFormLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.weightEdit)
        self.genreLabel = QtGui.QLabel(self.centralwidget)
        self.genreLabel.setText(QtGui.QApplication.translate("MainWindow", "Genre:", None, QtGui.QApplication.UnicodeUTF8))
        self.genreLabel.setObjectName(_fromUtf8("genreLabel"))
        self.infoFormLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.genreLabel)
        self.genreSelection = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genreSelection.sizePolicy().hasHeightForWidth())
        self.genreSelection.setSizePolicy(sizePolicy)
        self.genreSelection.setObjectName(_fromUtf8("genreSelection"))
        self.genreSelection.addItem(_fromUtf8(""))
        self.genreSelection.setItemText(0, QtGui.QApplication.translate("MainWindow", "Cyberpunk", None, QtGui.QApplication.UnicodeUTF8))
        self.genreSelection.addItem(_fromUtf8(""))
        self.genreSelection.setItemText(1, QtGui.QApplication.translate("MainWindow", "Hotrods and Guns", None, QtGui.QApplication.UnicodeUTF8))
        self.genreSelection.addItem(_fromUtf8(""))
        self.genreSelection.setItemText(2, QtGui.QApplication.translate("MainWindow", "Martial Arts", None, QtGui.QApplication.UnicodeUTF8))
        self.genreSelection.addItem(_fromUtf8(""))
        self.genreSelection.setItemText(3, QtGui.QApplication.translate("MainWindow", "Medieval Fantasy", None, QtGui.QApplication.UnicodeUTF8))
        self.genreSelection.addItem(_fromUtf8(""))
        self.genreSelection.setItemText(4, QtGui.QApplication.translate("MainWindow", "Modern Military", None, QtGui.QApplication.UnicodeUTF8))
        self.genreSelection.addItem(_fromUtf8(""))
        self.genreSelection.setItemText(5, QtGui.QApplication.translate("MainWindow", "Occult Horror", None, QtGui.QApplication.UnicodeUTF8))
        self.genreSelection.addItem(_fromUtf8(""))
        self.genreSelection.setItemText(6, QtGui.QApplication.translate("MainWindow", "Space Opera", None, QtGui.QApplication.UnicodeUTF8))
        self.genreSelection.addItem(_fromUtf8(""))
        self.genreSelection.setItemText(7, QtGui.QApplication.translate("MainWindow", "Teenage Romance", None, QtGui.QApplication.UnicodeUTF8))
        self.infoFormLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.genreSelection)
        self.gridLayout_2.addLayout(self.infoFormLayout, 2, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Character Points: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.cpSpin = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpSpin.sizePolicy().hasHeightForWidth())
        self.cpSpin.setSizePolicy(sizePolicy)
        self.cpSpin.setMinimum(0)
        self.cpSpin.setMaximum(10000)
        self.cpSpin.setObjectName(_fromUtf8("cpSpin"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cpSpin)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Skill Points:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.spSpin = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spSpin.sizePolicy().hasHeightForWidth())
        self.spSpin.setSizePolicy(sizePolicy)
        self.spSpin.setMaximum(100)
        self.spSpin.setObjectName(_fromUtf8("spSpin"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spSpin)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 1, 0, 1, 3)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Remaining Character Points:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.remainingCpEdit = QtGui.QLineEdit(self.centralwidget)
        self.remainingCpEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remainingCpEdit.sizePolicy().hasHeightForWidth())
        self.remainingCpEdit.setSizePolicy(sizePolicy)
        self.remainingCpEdit.setObjectName(_fromUtf8("remainingCpEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.remainingCpEdit)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Remaining Skill Points:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.remaingSpEdit = QtGui.QLineEdit(self.centralwidget)
        self.remaingSpEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remaingSpEdit.sizePolicy().hasHeightForWidth())
        self.remaingSpEdit.setSizePolicy(sizePolicy)
        self.remaingSpEdit.setObjectName(_fromUtf8("remaingSpEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.remaingSpEdit)
        self.gridLayout_2.addLayout(self.formLayout_2, 0, 1, 1, 2)
        self.notesFormLayout = QtGui.QFormLayout()
        self.notesFormLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.notesFormLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.notesFormLayout.setObjectName(_fromUtf8("notesFormLayout"))
        self.notesLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesLabel.sizePolicy().hasHeightForWidth())
        self.notesLabel.setSizePolicy(sizePolicy)
        self.notesLabel.setMinimumSize(QtCore.QSize(38, 0))
        self.notesLabel.setBaseSize(QtCore.QSize(38, 0))
        self.notesLabel.setMidLineWidth(0)
        self.notesLabel.setText(QtGui.QApplication.translate("MainWindow", "Notes:", None, QtGui.QApplication.UnicodeUTF8))
        self.notesLabel.setMargin(0)
        self.notesLabel.setObjectName(_fromUtf8("notesLabel"))
        self.notesFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.notesLabel)
        self.notesEdit = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(110)
        sizePolicy.setHeightForWidth(self.notesEdit.sizePolicy().hasHeightForWidth())
        self.notesEdit.setSizePolicy(sizePolicy)
        self.notesEdit.setAutoFormatting(QtGui.QTextEdit.AutoAll)
        self.notesEdit.setReadOnly(False)
        self.notesEdit.setObjectName(_fromUtf8("notesEdit"))
        self.notesFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.notesEdit)
        self.gridLayout_2.addLayout(self.notesFormLayout, 2, 1, 1, 2)
        self.skillsAttributesTab = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.skillsAttributesTab.sizePolicy().hasHeightForWidth())
        self.skillsAttributesTab.setSizePolicy(sizePolicy)
        self.skillsAttributesTab.setTabPosition(QtGui.QTabWidget.South)
        self.skillsAttributesTab.setTabShape(QtGui.QTabWidget.Rounded)
        self.skillsAttributesTab.setDocumentMode(False)
        self.skillsAttributesTab.setTabsClosable(False)
        self.skillsAttributesTab.setObjectName(_fromUtf8("skillsAttributesTab"))
        self.skills = QtGui.QWidget()
        self.skills.setObjectName(_fromUtf8("skills"))
        self.gridLayout_3 = QtGui.QGridLayout(self.skills)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.skillsTable = QtGui.QTableWidget(self.skills)
        self.skillsTable.setAlternatingRowColors(True)
        self.skillsTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.skillsTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.skillsTable.setObjectName(_fromUtf8("skillsTable"))
        self.skillsTable.setColumnCount(3)
        self.skillsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("MainWindow", "Skills Name", None, QtGui.QApplication.UnicodeUTF8))
        self.skillsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("MainWindow", "Skills Cost", None, QtGui.QApplication.UnicodeUTF8))
        self.skillsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("MainWindow", "Character Skill", None, QtGui.QApplication.UnicodeUTF8))
        self.skillsTable.setHorizontalHeaderItem(2, item)
        self.skillsTable.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.skillsTable, 0, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buySkillButton = QtGui.QPushButton(self.skills)
        self.buySkillButton.setText(QtGui.QApplication.translate("MainWindow", "Buy Skill", None, QtGui.QApplication.UnicodeUTF8))
        self.buySkillButton.setObjectName(_fromUtf8("buySkillButton"))
        self.gridLayout.addWidget(self.buySkillButton, 0, 0, 1, 1)
        self.sellSkillButton = QtGui.QPushButton(self.skills)
        self.sellSkillButton.setText(QtGui.QApplication.translate("MainWindow", "Sell Skill", None, QtGui.QApplication.UnicodeUTF8))
        self.sellSkillButton.setObjectName(_fromUtf8("sellSkillButton"))
        self.gridLayout.addWidget(self.sellSkillButton, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.skillsAttributesTab.addTab(self.skills, _fromUtf8(""))
        self.attributes = QtGui.QWidget()
        self.attributes.setObjectName(_fromUtf8("attributes"))
        self.skillsAttributesTab.addTab(self.attributes, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.skillsAttributesTab, 7, 0, 1, 3)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 3, 0, 1, 3)
        self.derivedValuesFormLayout = QtGui.QFormLayout()
        self.derivedValuesFormLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.derivedValuesFormLayout.setObjectName(_fromUtf8("derivedValuesFormLayout"))
        self.cvLabel = QtGui.QLabel(self.centralwidget)
        self.cvLabel.setText(QtGui.QApplication.translate("MainWindow", "Combat:", None, QtGui.QApplication.UnicodeUTF8))
        self.cvLabel.setObjectName(_fromUtf8("cvLabel"))
        self.derivedValuesFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.cvLabel)
        self.combatEdit = QtGui.QLineEdit(self.centralwidget)
        self.combatEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combatEdit.sizePolicy().hasHeightForWidth())
        self.combatEdit.setSizePolicy(sizePolicy)
        self.combatEdit.setObjectName(_fromUtf8("combatEdit"))
        self.derivedValuesFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.combatEdit)
        self.defenseEdit = QtGui.QLineEdit(self.centralwidget)
        self.defenseEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defenseEdit.sizePolicy().hasHeightForWidth())
        self.defenseEdit.setSizePolicy(sizePolicy)
        self.defenseEdit.setObjectName(_fromUtf8("defenseEdit"))
        self.derivedValuesFormLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.defenseEdit)
        self.svLabel = QtGui.QLabel(self.centralwidget)
        self.svLabel.setText(QtGui.QApplication.translate("MainWindow", "Shock:", None, QtGui.QApplication.UnicodeUTF8))
        self.svLabel.setObjectName(_fromUtf8("svLabel"))
        self.derivedValuesFormLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.svLabel)
        self.shockEdit = QtGui.QLineEdit(self.centralwidget)
        self.shockEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shockEdit.sizePolicy().hasHeightForWidth())
        self.shockEdit.setSizePolicy(sizePolicy)
        self.shockEdit.setObjectName(_fromUtf8("shockEdit"))
        self.derivedValuesFormLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.shockEdit)
        self.dvLabel = QtGui.QLabel(self.centralwidget)
        self.dvLabel.setText(QtGui.QApplication.translate("MainWindow", "Defense:", None, QtGui.QApplication.UnicodeUTF8))
        self.dvLabel.setObjectName(_fromUtf8("dvLabel"))
        self.derivedValuesFormLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.dvLabel)
        self.gridLayout_2.addLayout(self.derivedValuesFormLayout, 4, 1, 1, 1)
        self.healthEnergyFormLayout = QtGui.QFormLayout()
        self.healthEnergyFormLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.healthEnergyFormLayout.setObjectName(_fromUtf8("healthEnergyFormLayout"))
        self.healthEdit = QtGui.QLineEdit(self.centralwidget)
        self.healthEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.healthEdit.sizePolicy().hasHeightForWidth())
        self.healthEdit.setSizePolicy(sizePolicy)
        self.healthEdit.setObjectName(_fromUtf8("healthEdit"))
        self.healthEnergyFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.healthEdit)
        self.energyLabel = QtGui.QLabel(self.centralwidget)
        self.energyLabel.setText(QtGui.QApplication.translate("MainWindow", "Energy:", None, QtGui.QApplication.UnicodeUTF8))
        self.energyLabel.setObjectName(_fromUtf8("energyLabel"))
        self.healthEnergyFormLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.energyLabel)
        self.energyEdit = QtGui.QLineEdit(self.centralwidget)
        self.energyEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.energyEdit.sizePolicy().hasHeightForWidth())
        self.energyEdit.setSizePolicy(sizePolicy)
        self.energyEdit.setObjectName(_fromUtf8("energyEdit"))
        self.healthEnergyFormLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.energyEdit)
        self.healthLabel = QtGui.QLabel(self.centralwidget)
        self.healthLabel.setText(QtGui.QApplication.translate("MainWindow", "Health:", None, QtGui.QApplication.UnicodeUTF8))
        self.healthLabel.setObjectName(_fromUtf8("healthLabel"))
        self.healthEnergyFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.healthLabel)
        self.gridLayout_2.addLayout(self.healthEnergyFormLayout, 4, 2, 1, 1)
        self.statFormLayout = QtGui.QFormLayout()
        self.statFormLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.statFormLayout.setObjectName(_fromUtf8("statFormLayout"))
        self.bodyLabel = QtGui.QLabel(self.centralwidget)
        self.bodyLabel.setText(QtGui.QApplication.translate("MainWindow", "Body:", None, QtGui.QApplication.UnicodeUTF8))
        self.bodyLabel.setObjectName(_fromUtf8("bodyLabel"))
        self.statFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.bodyLabel)
        self.bodySpin = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bodySpin.sizePolicy().hasHeightForWidth())
        self.bodySpin.setSizePolicy(sizePolicy)
        self.bodySpin.setMinimum(1)
        self.bodySpin.setMaximum(12)
        self.bodySpin.setObjectName(_fromUtf8("bodySpin"))
        self.statFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.bodySpin)
        self.mindLabel = QtGui.QLabel(self.centralwidget)
        self.mindLabel.setText(QtGui.QApplication.translate("MainWindow", "Mind:", None, QtGui.QApplication.UnicodeUTF8))
        self.mindLabel.setObjectName(_fromUtf8("mindLabel"))
        self.statFormLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.mindLabel)
        self.mindSpin = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mindSpin.sizePolicy().hasHeightForWidth())
        self.mindSpin.setSizePolicy(sizePolicy)
        self.mindSpin.setMinimum(1)
        self.mindSpin.setMaximum(12)
        self.mindSpin.setObjectName(_fromUtf8("mindSpin"))
        self.statFormLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.mindSpin)
        self.soulLabel = QtGui.QLabel(self.centralwidget)
        self.soulLabel.setText(QtGui.QApplication.translate("MainWindow", "Soul:", None, QtGui.QApplication.UnicodeUTF8))
        self.soulLabel.setObjectName(_fromUtf8("soulLabel"))
        self.statFormLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.soulLabel)
        self.soulSpin = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.soulSpin.sizePolicy().hasHeightForWidth())
        self.soulSpin.setSizePolicy(sizePolicy)
        self.soulSpin.setMinimum(1)
        self.soulSpin.setMaximum(12)
        self.soulSpin.setObjectName(_fromUtf8("soulSpin"))
        self.statFormLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.soulSpin)
        self.gridLayout_2.addLayout(self.statFormLayout, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 573, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSkills = QtGui.QMenu(self.menubar)
        self.menuSkills.setTitle(QtGui.QApplication.translate("MainWindow", "Skills", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSkills.setObjectName(_fromUtf8("menuSkills"))
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setMenuRole(QtGui.QAction.QuitRole)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionLoad_Skillset = QtGui.QAction(MainWindow)
        self.actionLoad_Skillset.setText(QtGui.QApplication.translate("MainWindow", "Load Skillset...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Skillset.setObjectName(_fromUtf8("actionLoad_Skillset"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSkills.addAction(self.actionLoad_Skillset)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSkills.menuAction())

        self.retranslateUi(MainWindow)
        self.skillsAttributesTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        item = self.skillsTable.horizontalHeaderItem(0)
        item = self.skillsTable.horizontalHeaderItem(1)
        item = self.skillsTable.horizontalHeaderItem(2)
        self.skillsAttributesTab.setTabText(self.skillsAttributesTab.indexOf(self.skills), QtGui.QApplication.translate("MainWindow", "Skills", None, QtGui.QApplication.UnicodeUTF8))
        self.skillsAttributesTab.setTabText(self.skillsAttributesTab.indexOf(self.attributes), QtGui.QApplication.translate("MainWindow", "Attributes", None, QtGui.QApplication.UnicodeUTF8))

